import http from 'node:http';
import crypto from 'node:crypto';

const PORT = Number(process.env.PORT || 3000);
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const AI_KEY = process.env.OPENAI_API_KEY || '';
const JWT_SECRET = process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');
const MODEL = process.env.OPENAI_MODEL || 'gpt-5';

function json(res, status, body) { const text = JSON.stringify(body); res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}); res.end(text); }
function tokenFor(payload) { const h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'); const p=Buffer.from(JSON.stringify({...payload,exp:Math.floor(Date.now()/1000)+86400})).toString('base64url'); const s=crypto.createHmac('sha256',JWT_SECRET).update(`${h}.${p}`).digest('base64url'); return `${h}.${p}.${s}`; }
function verifyToken(token) { const [h,p,s]=String(token||'').split('.'); if(!h||!p||!s)return null; const expected=crypto.createHmac('sha256',JWT_SECRET).update(`${h}.${p}`).digest('base64url'); if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null; const data=JSON.parse(Buffer.from(p,'base64url')); return data.exp>Date.now()/1000?data:null; }
function verifyTelegram(initData) { if(!BOT_TOKEN||!initData) return null; const params=new URLSearchParams(initData); const hash=params.get('hash'); params.delete('hash'); const check=Array.from(params.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'); const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest(); const calc=crypto.createHmac('sha256',secret).update(check).digest('hex'); if(!hash||!crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(calc)))return null; const user=JSON.parse(params.get('user')||'{}'); return user.id?user:null; }
async function body(req) { let raw=''; for await(const chunk of req) raw+=chunk; return raw?JSON.parse(raw):{}; }
async function generate({narrative,goal,area,obstacles,minutesPerDay,energy}) { if(!AI_KEY) throw new Error('AI key is not configured'); const prompt=`Ты создаёшь персональную RPG-кампанию реальной жизни.\nИстория: ${narrative.slice(0,3500)}\nЦель: ${goal.slice(0,300)}\nСфера: ${area}\nПрепятствия: ${(obstacles||[]).join(', ')}\nВремени в день: ${minutesPerDay} минут\nЭнергия: ${energy}\nВерни только JSON-массив из 5 объектов: title, why, details, xpReward. Каждый квест должен быть конкретным, выполнимым за указанное время и прямо вытекать из истории человека.`; const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${AI_KEY}`},body:JSON.stringify({model:MODEL,instructions:'Отвечай только валидным JSON без markdown.',input:prompt,store:false})}); if(!r.ok)throw new Error(`AI ${r.status}`); const d=await r.json(); const text=d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||''; const parsed=JSON.parse(text.slice(text.indexOf('['),text.lastIndexOf(']')+1)); return parsed.slice(0,5).map((q,i)=>({title:String(q.title||'Следующий ход').slice(0,120),why:String(q.why||'Это следующий конкретный шаг по твоей истории.').slice(0,220),details:String(q.details||'Сделай действие и отметь результат.').slice(0,320),xpReward:Math.max(10,Math.min(50,Number(q.xpReward)||10)),id:`ai-${i}`})); }
const server=http.createServer(async(req,res)=>{ if(req.method==='OPTIONS')return json(res,204,{}); try { if(req.url==='/health')return json(res,200,{ok:true,ai:!!AI_KEY}); if(req.method==='POST'&&req.url==='/auth/telegram'){const b=await body(req); const u=verifyTelegram(b.initData); if(!u)return json(res,401,{error:'Telegram auth failed'}); return json(res,200,{token:tokenFor({userId:u.id,name:u.first_name||''})});} if(req.method==='POST'&&req.url==='/campaign/generate'){const auth=verifyToken(req.headers.authorization?.replace(/^Bearer\s+/i,'')); if(!auth)return json(res,401,{error:'Unauthorized'}); const b=await body(req); if(typeof b.narrative!=='string'||b.narrative.trim().length<20||typeof b.goal!=='string'||!b.goal.trim())return json(res,400,{error:'Narrative and goal are required'}); const quests=await generate(b); return json(res,201,{campaign:{title:'Твоя личная кампания',area:b.area||'growth',goal:b.goal,cadenceMinutes:b.minutesPerDay||20,adaptiveRule:'Следующий ход меняется по твоим отметкам и рефлексии.'},quests});} return json(res,404,{error:'Not found'}); } catch(e) { console.error(e); return json(res,500,{error:'Server error'}); } });
server.listen(PORT,()=>console.log(`LifeRPG AI backend listening on ${PORT}`));
